FROM node:18.13.0 AS build
#FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
#COPY package.json yarn.lock ./
RUN yarn install
COPY . .
RUN yarn build

FROM nginx AS serve
COPY --from=build /app/dist /usr/share/nginx/html
#COPY ./nginx-local.conf /etc/nginx/conf.d/default.conf
COPY ./frontnginx/server.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx","-g", "daemon off;"]

