server:
  port: 8761

spring:
  application:
    name: social-network-discovery
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: social-network-discovery/config/

eureka:
  dashboard:
    path: /dashboard/
    enabled: true
  client:
    enabled: true
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://176.123.168.208:8761/eureka/