server:
  #  port: 8082
  port: 0

spring:
  application:
    name: social-network-friends
  datasource:
    #    url: jdbc:postgresql://localhost:5432/social-network-friend
    url: jdbc:postgresql://89.111.174.153:5432/social-network-friend
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      schema: friends_schema
      connection-init-sql: create schema if not exists friends_schema
      connection-timeout: 10000



  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml

eureka:
  client:
    enabled: true
    service-url:
      #      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://89.111.174.153:8761/eureka/
